capstone/capstone/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("counters.urls", namespace='counters')),

]

capstone/counters/urls.py
from django.urls import path, reverse_lazy
from django.views.generic import DeleteView
from .models import Counter, Reading
from django.contrib.auth.decorators import login_required

from .views import (
    CounterDetailView,
    SummaryView,
    AddCounter,
    CounterUpdateView,
    login_view,
    logout_view,
    register,
    index_view,
    add_readings,
)

app_name = "counters"

urlpatterns = [
    # User
    path("", index_view, name="index"),
    path("login", login_view, name="login"),
    path("logout", logout_view, name="logout"),
    path("register", register, name="register"),
    path("dashboard/", SummaryView.as_view(), name="dashboard"),
    # Counters urls
    path("counter/<int:pk>", CounterDetailView.as_view(), name="counter-detail"),
    path("counter/add", AddCounter.as_view(), name="counter-add"),
    path("counter/<int:pk>/edit", CounterUpdateView.as_view(), name="counter-edit"),
    path(
        "counter/<int:pk>/delete/",
        DeleteView.as_view(
            model=Counter,
            success_url=reverse_lazy("counters:dashboard"),
            template_name="counters/generic_delete.html",
        ),
        name="counter-delete",
    ),
    # Reading urls
    path("readings/add", add_readings, name="readings-add"),
    path(
        "reading/<int:pk>/delete/",
        login_required(
            DeleteView.as_view(
                model=Reading,
                success_url=reverse_lazy("counters:dashboard"),
                template_name="counters/generic_delete.html",
            )
        ),
        name="reading-delete",
    ),
]

capstone/counters/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Counter(models.Model):
    user = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, related_name="counters"
    )
    title = models.CharField(max_length=60)
    unit = models.CharField(max_length=60, blank=True, null=True)

    def __str__(self):
        return f"{self.title}"


class Reading(models.Model):
    class Meta:
        ordering = ("-date",)

    counter = models.ForeignKey(
        "Counter", related_name="readings", on_delete=models.CASCADE
    )
    date = models.DateField()
    value = models.DecimalField(max_digits=10, decimal_places=2)
    usage = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    def save(self, *args, **kwargs):
        super(Reading, self).save(
            *args, **kwargs
        )  # Save the object first to get a valid pk
        self.usage = self.usage_in_units()  # Now calculate the usage using the valid pk
        super(Reading, self).save(
            update_fields=["usage"]
        )  # Save the object again with updated usage field

    def __str__(self):
        return f"{self.counter.title} {self.value} on {self.date}"

    def get_previous_reading(self):
        return self.counter.readings.filter(pk__lt=self.pk).order_by("-pk").first()

    def usage_in_units(self):
        previous_reading = self.get_previous_reading()
        if previous_reading:
            return float(self.value) - float(previous_reading.value)
        else:
            return 0


class Price(models.Model):
    class Meta:
        ordering = ("date",)

    counter = models.ForeignKey(
        "Counter", related_name="prices", on_delete=models.CASCADE
    )
    date = models.DateField()
    price_per_unit = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    price_per_month = models.DecimalField(max_digits=5, decimal_places=2, default=0)


class Payment(models.Model):
    counter = models.ForeignKey(
        "Counter", related_name="payments", on_delete=models.CASCADE
    )
    reading = models.OneToOneField(
        "Reading", related_name="payment", on_delete=models.CASCADE
    )
    price = models.ForeignKey(
        "Price", related_name="payments", on_delete=models.CASCADE
    )
    amount = models.DecimalField(max_digits=10, decimal_places=2)

capstone/counters/forms.py
from django.forms import ModelForm, DateField
from django.forms.widgets import DateInput
from .models import Reading, Counter, Price


class ReadingForm(ModelForm):
    class Meta:
        model = Reading
        fields = "__all__"

        widgets = {
            "date": DateInput(attrs={"type": "date"}),
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)  # Get the user from the kwargs
        super().__init__(*args, **kwargs)
        if user:
            self.fields["counter"].queryset = Counter.objects.filter(user=user)


class UpdateCounterForm(ModelForm):
    class Meta:
        model = Counter
        exclude = ["user"]


class AddCounterPriceForm(ModelForm):
    class Meta:
        model = Price
        exclude = ["counter", "date"]


class AddCounterReadingForm(ModelForm):
    class Meta:
        model = Reading
        exclude = ["counter", "date", "usage"]


class AddCounterForm(UpdateCounterForm):
    class Meta:
        model = Counter
        exclude = ["user"]

    initial_date = DateField(widget=DateInput(attrs={"type": "date"}))

capstone/counters/views.py
import calendar
import json
from datetime import datetime
# from types import NoneType

from django.db import IntegrityError
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, UpdateView, View, CreateView
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import (
    HttpResponse,
    HttpResponseRedirect,
    JsonResponse,
    HttpResponseForbidden,
    HttpResponseBadRequest,
)
from django.core.serializers import serialize
from django.contrib.auth import get_user_model

from django.db.models import Sum
from django.db.models.functions import ExtractMonth, ExtractYear

from .forms import (
    ReadingForm,
    AddCounterForm,
    AddCounterPriceForm,
    AddCounterReadingForm,
    UpdateCounterForm,
)
from .models import Counter, Reading, Price, Payment

from django.db.models import OuterRef, Subquery, Max


def index_view(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse("counters:dashboard"))
    else:
        return render(request, "counters/index.html")


def login_view(request):
    if request.method == "POST":
        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("counters:dashboard"))
        else:
            return render(
                request,
                "counters/login.html",
                {"message": "Invalid username and/or password."},
            )
    else:
        return render(request, "counters/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("counters:login"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        if not username:
            return render(
                request, "counters/register.html", {"message": "Username is required"}
            )

        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if len(password) < 8:
            return render(
                request,
                "counters/register.html",
                {"message": "Passwords must contain at least 8 characters."},
            )

        if password != confirmation:
            return render(
                request, "counters/register.html", {"message": "Passwords must match."}
            )

        # Attempt to create new user
        try:
            user = get_user_model().objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(
                request,
                "counters/register.html",
                {"message": "Username already taken."},
            )
        login(request, user)
        return HttpResponseRedirect(reverse("counters:dashboard"))
    else:
        return render(request, "counters/register.html")


class CounterDetailView(DetailView):
    model = Counter

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(user=self.request.user)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        counter = context["object"]
        readings = (
            Reading.objects.filter(counter=counter, usage__gt=0)
            .annotate(month=ExtractMonth("date"))
            .values("month", "usage")
            .order_by("date")
        )
        readings_month = [
            calendar.month_name[reading.get("month")] for reading in readings
        ]
        readings_usage = [float(reading.get("usage")) for reading in readings]

        context["readings_month"] = readings_month
        context["readings_usage"] = readings_usage
        return context


class AddCounter(LoginRequiredMixin, CreateView):
    form_class = AddCounterForm
    template_name = "counters/generic_update.html"
    success_url = reverse_lazy("counters:dashboard")

    def form_valid(self, form):
        if form.is_valid():
            form.instance.user = self.request.user
            response = super().form_valid(form)

            # Get the counter by its name
            counter_name = form.cleaned_data["title"]
            try:
                counter = Counter.objects.get(
                    user=self.request.user, title=counter_name
                )
            except Counter.DoesNotExist:
                # Handle the case when the counter with the given name doesn't exist
                # (e.g., show an error message or redirect to an error page)
                raise ValueError("Counter with the given name does not exist.")

            # Validate the AddCounterPriceForm
            price_form = AddCounterPriceForm(self.request.POST)
            if price_form.is_valid():
                Price.objects.create(
                    counter=counter,
                    date=form.cleaned_data["initial_date"],
                    price_per_unit=price_form.cleaned_data["price_per_unit"],
                    price_per_month=price_form.cleaned_data["price_per_month"],
                )

            # Validate the AddCounterReadingForm
            reading_form = AddCounterReadingForm(self.request.POST)
            if reading_form.is_valid():
                Reading.objects.create(
                    counter=counter,
                    date=form.cleaned_data["initial_date"],
                    value=reading_form.cleaned_data["value"],
                )

            return response
        return self.form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context[
            "price_form"
        ] = AddCounterPriceForm()  # Include the CounterPriceForm in the context
        context["reading_form"] = AddCounterReadingForm()
        return context


class SummaryView(ListView):
    model = Counter
    template_name = "counters/summary.html"

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(user=self.request.user)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        latest_reading_date = latest_reading_date_for_user_counters(self.request.user)
        if latest_reading_date:
            context["latest_reading_date"] = latest_reading_date.strftime("%Y-%m-%d")
        context["counter_form"] = AddCounterForm()
        context["payments_per_month"] = (
            Reading.objects.filter(counter__user=self.request.user, usage__gt=0)
            .annotate(month=ExtractMonth("date"), year=ExtractYear("date"))
            .values("month", "year")
            .annotate(total_payment=Sum("payment__amount"))
            .order_by("month")
        )
        return context


def latest_reading_date_for_user_counters(user):
    return Reading.objects.filter(counter__user=user).aggregate(
        latest_date=Max("date")
    )["latest_date"]


def add_readings(request):
    if request.method == "POST":
        readings_date = datetime.strptime(request.POST.get("date"), "%Y-%m-%d")
        for counter in request.user.counters.all():
            # Only one reading per month if this not initial reading
            if counter.readings.exists() and counter.readings.count() > 1:
                latest_reading = counter.readings.latest("pk")

                # Return HttpResponseBadRequest if value of previous reading i greater then new value
                if float(latest_reading.value) > float(request.POST.get(counter.title)):
                    return HttpResponseBadRequest()

                # Delete the latest reading if reading in same month
                if latest_reading.date.month == readings_date.month:
                    latest_reading.delete()

            Reading.objects.create(
                counter=counter,
                date=readings_date,
                value=request.POST.get(counter.title),
            )

            latest_reading = counter.readings.latest("pk")

            # Adding Payment
            Payment.objects.create(
                counter=counter,
                reading=latest_reading,
                price=counter.prices.last(),
                amount=calculate_reading_payment(latest_reading),
            )

        return redirect(reverse_lazy("counters:dashboard"))


def calculate_reading_payment(reading):
    if reading.get_previous_reading():
        if reading.usage_in_units():
            total = reading.usage_in_units() * float(
                reading.counter.prices.last().price_per_unit
            )
            return (
                total + float(reading.counter.prices.last().price_per_month)
                if reading.counter.prices.last().price_per_month
                else total
            )
        return reading.counter.prices.last().price_per_month


class CounterUpdateView(UpdateView):
    form_class = UpdateCounterForm
    template_name = "counters/generic_update.html"

    def get_queryset(self):
        return Counter.objects.filter(user=self.request.user)

    def get_success_url(self):
        return reverse_lazy("counters:counter-detail", kwargs={"pk": self.object.pk})

capstone/counters/templates/counters/account.html
{% extends "counters/base.html" %}

{% block content %}
<div class="container text-center" style="height: 80vh;">
    <div class="row align-items-center justify-content-center" style="height: 100%;">
        <div class="col col-lg-6">
            <div class="card border-0 shadow rounded">
                <div class="card-body">
                    {% block form %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

capstone/counters/templates/counters/base.html
<!DOCTYPE html>
<html>

<head>
    <title>
        {% block meta_title %}Counters app{% endblock %}
    </title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>
<body>
<nav class="navbar bg-dark border-bottom border-bottom-dark navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">

    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'counters:index' %}">Counters</a>
        {% if user.is_authenticated %}
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'counters:dashboard' %}">Dashboard</a>
                </li>
            </ul>
            <span class="navbar-text mx-5">
        {{ user }}
        </span>

            <a class="nav-link" href="{% url 'counters:logout' %}">
                <button type="button" class="btn btn-outline-light">Logout</button>
            </a>
            {% else %}
            <a class="nav-link" href="{% url 'counters:login' %}">
                <button type="button" class="btn btn-outline-light">Login</button>
            </a>
            {% endif %}
        </div>
    </div>
</nav>
{% block content %}{% endblock %}
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
</html>

capstone/counters/templates/counters/counter_detail.html
{% extends "counters/dashboard.html" %}
{% load custom_tags %}

{% block data %}
<div class="card border-0 shadow rounded">
    <div class="card-body">
        {% with counter=object %}
        <h5 class="card-title">{{ counter.title }}</h5>
        <p>Unit: {{ counter.unit }}</p>
        <p>Price per {{ counter.unit }}: {{ counter.prices.last.price_per_unit }}</p>
        <p>Price per month: {{ counter.prices.last.price_per_month }}</p>
        <a href="{% url 'counters:counter-edit' counter.id %}">edit</a>
        <a href="{% url 'counters:counter-delete' counter.id %}">delete</a>
        <div class="row my-5">

            <div class="col-12">
                <div class="card border-0 shadow rounded">
                    <div class="card-body">
                        <h6 class="mb-0 ">{{ counter.title }} usage</h6>
                        <div class="chart">
                            <canvas id="chart-usage" class="chart-canvas"></canvas>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12">
                {% with readings=counter.readings.all %}
                {% include 'counters/partials/readings_table.html' %}
                {% endwith %}
            </div>
        </div>


        <div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <script>
var ctx = document.getElementById("chart-usage");
var readings_month = {{ readings_month|as_json|safe }};
var readings_usage = {{ readings_usage|as_json }};

console.log(readings_month);
console.log(readings_usage);

    new Chart(ctx, {
      type: "line",
        data: {
        labels: readings_month,
        datasets: [{
          label: "Usage",
          backgroundColor: "transparent",
          data: readings_usage,
        }],
      },
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
          legend: {
            display: false,
          }
        },
      },
    });



        </script>
        {% endwith %}
    </div>
</div>
{% endblock %}

capstone/counters/templates/counters/dashboard.html
{% extends "counters/base.html" %}
{% block content %}

<div>
    {% block data %}
    {% endblock %}
</div>
{% endblock %}

capstone/counters/templates/counters/generic_delete.html
{% extends "counters/dashboard.html" %}
{% block data %}
<h1>Confirm removing "{{ object }}"</h1>
<form method="post" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">delete</button>
</form>
{% endblock %}

capstone/counters/templates/counters/generic_update.html
{% extends "counters/dashboard.html" %}
{% block data %}
<div class="row m-2">
    <div class="col-auto">
        <div class="card border-0 shadow rounded">
            <div class="card-body">
                <form method="post" action="">
                    {% csrf_token %}
                    {{ form.as_p }}
                    {{ price_form.as_p }}
                    {{ reading_form.as_p }}
                    <button type="submit">save</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

capstone/counters/templates/counters/index.html
{% extends "counters/base.html" %}

{% block content %}
<div class="container">
    <h1>Home Counters Management Application</h1>

    <p>Welcome to the Home Counters Management Application! This Django project was developed as the capstone project
        for the
        CS50 Web Programming Course. The application enables users to efficiently track and
        manage various home counters, such as hot-water, electricity, cold-water, and more. Users can add their own
        counters,
        set monthly payments, specify payment per-unit consumption (e.g., kWh for electricity or m3 for water), and
        monitor
        usage trends. The application facilitates accurate monthly payment calculations and provides a detailed overview
        of
        consumption and payment history. It is designed to provide a user-friendly interface for managing
        counter details, recording readings, and calculating accurate monthly payments based on consumption.</p>

    <h3>Key Features</h3>
    <ul>

        <li>Multiple Counter Types: Add and manage different types of home counters, including hot-water, electricity,
            gas,
            cold-water, and more. The application is designed to be flexible and allows users to customize counter types
            to their
            specific needs.
        </li>
        <li>Payment per-Unit Consumption: Specify the price per-unit consumption (e.g., kWh, m3) for each counter. The
            application
            automatically calculates the total payment based on the consumed units, ensuring accurate billing.
        </li>
        <li>Usage Monitoring and Trend Analysis: Record readings for each counter periodically, and the application
            tracks and
            displays consumption patterns over time. Users can analyze usage trends and identify any inefficiencies or
            unusual
            patterns.
        </li>
    </ul>
</div>
{% endblock %}

capstone/counters/templates/counters/login.html
{% extends "counters/account.html" %}

{% block form %}

<h2>Login</h2>

{% if message %}
<div>{{ message }}</div>
{% endif %}

<form action="{% url 'counters:login' %}" method="post">
    {% csrf_token %}
    <div class="form-floating mb-3">
        <input type="text" name="username" class="form-control" id="floatingInput" placeholder="Username">
        <label for="floatingInput">Username</label>
    </div>
    <div class="form-floating">
        <input type="password" name="password" class="form-control" id="floatingPassword" placeholder="Password">
        <label for="floatingPassword">Password</label>
    </div>
    <div class="my-3">
        <button class="btn btn-primary" type="submit">Login</button>
    </div>
</form>

Don't have an account? <a href="{% url 'counters:register' %}">Register here.</a>

{% endblock %}

capstone/counters/templates/counters/register.html
{% extends "counters/account.html" %}

{% block form %}

<h2>Register</h2>

{% if message %}
<div>{{ message }}</div>
{% endif %}

<form action="{% url 'counters:register' %}" method="post">
    {% csrf_token %}
    <div class="form-floating mb-3">
        <input type="text" name="username" class="form-control" id="floatingUsername" placeholder="Username" required
               autofocus>
        <label for="floatingUsername">Username</label>
    </div>
    <div class="form-floating mb-3">
        <input type="email" name="email" class="form-control" id="floatingEmail" placeholder="name@example.com">
        <label for="floatingEmail">Email address</label>
    </div>
    <div class="form-floating mb-3">
        <input type="password" name="password" class="form-control" id="floatingPassword" placeholder="Password"
               required>
        <label for="floatingPassword">Password</label>
    </div>
    <div class="form-floating mb-3">
        <input type="password" name="confirmation" class="form-control" id="floatingPasswordConfirm"
               placeholder="Confirm Password" required>
        <label for="floatingPasswordConfirm">Confirm Password</label>
    </div>
    <button class="btn btn-primary" type="submit">Register</button>
</form>

Already have an account? <a href="{% url 'counters:login' %}">Log In here.</a>

{% endblock %}

capstone/counters/templates/counters/summary.html
{% extends "counters/dashboard.html" %}
{% load custom_tags %}
{% block data %}
{% with counters=object_list%}
<div class="row m-2 g-2">
    {% if counters %}
    <div class="col-sm-12 col-lg-6">
        <div class="card border-0 shadow rounded">
            <div class="card-body">
                <h5 class="card-title">Latest Payments</h5>
                <table class="table">
                    <tbody>
                    {% for data in payments_per_month %}
                    <tr scope="col">
                        <th scope="col">{{ data.year }}</th>
                        <th scope="col">{{ data.month|month_name }}</th>
                        <td scope="col">{{ data.total_payment|floatformat:2 }}zł</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                    {% include 'counters/partials/readings_add_modal.html' %}
                </div>
            </div>
        </div>
    </div>
    {% endif %}
    <div class="col-sm-12 col-lg-6">
        <div class="card border-0 shadow rounded">
            <div class="card-body">
                {% include 'counters/partials/counters_table.html' %}
                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                    <button type="button" onclick="location.href='{% url 'counters:counter-add' %}';"
                            class="btn btn-primary">Add Counter
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endwith %}
{% endblock %}