capstone/capstone/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("counters.urls", namespace='counters')),

]

capstone/counters/urls.py
from django.urls import path, reverse_lazy
from django.views.generic import DeleteView
from .models import Counter, Reading
from django.contrib.auth.decorators import login_required

from .views import (
    CounterDetailView,
    SummaryView,
    AddCounter,
    CounterUpdateView,
    login_view,
    logout_view,
    register,
    index_view,
    add_readings,
)

app_name = "counters"

urlpatterns = [
    # User
    path("", index_view, name="index"),
    path("login", login_view, name="login"),
    path("logout", logout_view, name="logout"),
    path("register", register, name="register"),
    path("dashboard/", SummaryView.as_view(), name="dashboard"),
    # Counters urls
    path("counter/<int:pk>", CounterDetailView.as_view(), name="counter-detail"),
    path("counter/add", AddCounter.as_view(), name="counter-add"),
    path("counter/<int:pk>/edit", CounterUpdateView.as_view(), name="counter-edit"),
    path(
        "counter/<int:pk>/delete/",
        DeleteView.as_view(
            model=Counter,
            success_url=reverse_lazy("counters:dashboard"),
            template_name="counters/generic_delete.html",
        ),
        name="counter-delete",
    ),
    # Reading urls
    path("readings/add", add_readings, name="readings-add"),
    path(
        "reading/<int:pk>/delete/",
        login_required(
            DeleteView.as_view(
                model=Reading,
                success_url=reverse_lazy("counters:dashboard"),
                template_name="counters/generic_delete.html",
            )
        ),
        name="reading-delete",
    ),
]

capstone/counters/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Counter(models.Model):
    user = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, related_name="counters"
    )
    title = models.CharField(max_length=60)
    unit = models.CharField(max_length=60, blank=True, null=True)

    def __str__(self):
        return f"{self.title}"


class Reading(models.Model):
    class Meta:
        ordering = ("-date",)

    counter = models.ForeignKey(
        "Counter", related_name="readings", on_delete=models.CASCADE
    )
    date = models.DateField()
    value = models.DecimalField(max_digits=10, decimal_places=2)
    usage = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    def save(self, *args, **kwargs):
        super(Reading, self).save(
            *args, **kwargs
        )  # Save the object first to get a valid pk
        self.usage = self.usage_in_units()  # Now calculate the usage using the valid pk
        super(Reading, self).save(
            update_fields=["usage"]
        )  # Save the object again with updated usage field

    def __str__(self):
        return f"{self.counter.title} {self.value} on {self.date}"

    def get_previous_reading(self):
        return self.counter.readings.filter(pk__lt=self.pk).order_by("-pk").first()

    def usage_in_units(self):
        previous_reading = self.get_previous_reading()
        if previous_reading:
            return float(self.value) - float(previous_reading.value)
        else:
            return 0


class Price(models.Model):
    class Meta:
        ordering = ("date",)

    counter = models.ForeignKey(
        "Counter", related_name="prices", on_delete=models.CASCADE
    )
    date = models.DateField()
    price_per_unit = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    price_per_month = models.DecimalField(max_digits=5, decimal_places=2, default=0)


class Payment(models.Model):
    counter = models.ForeignKey(
        "Counter", related_name="payments", on_delete=models.CASCADE
    )
    reading = models.OneToOneField(
        "Reading", related_name="payment", on_delete=models.CASCADE
    )
    price = models.ForeignKey(
        "Price", related_name="payments", on_delete=models.CASCADE
    )
    amount = models.DecimalField(max_digits=10, decimal_places=2)

capstone/counters/forms.py
from django.forms import ModelForm, DateField
from django.forms.widgets import DateInput
from .models import Reading, Counter, Price


class ReadingForm(ModelForm):
    class Meta:
        model = Reading
        fields = "__all__"

        widgets = {
            "date": DateInput(attrs={"type": "date"}),
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)  # Get the user from the kwargs
        super().__init__(*args, **kwargs)
        if user:
            self.fields["counter"].queryset = Counter.objects.filter(user=user)


class UpdateCounterForm(ModelForm):
    class Meta:
        model = Counter
        exclude = ["user"]


class AddCounterPriceForm(ModelForm):
    class Meta:
        model = Price
        exclude = ["counter", "date"]


class AddCounterReadingForm(ModelForm):
    class Meta:
        model = Reading
        exclude = ["counter", "date", "usage"]


class AddCounterForm(UpdateCounterForm):
    class Meta:
        model = Counter
        exclude = ["user"]

    initial_date = DateField(widget=DateInput(attrs={"type": "date"}))

capstone/counters/views.py
import calendar
import json
from datetime import datetime
# from types import NoneType

from django.db import IntegrityError
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, UpdateView, View, CreateView
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import (
    HttpResponse,
    HttpResponseRedirect,
    JsonResponse,
    HttpResponseForbidden,
    HttpResponseBadRequest,
)
from django.core.serializers import serialize
from django.contrib.auth import get_user_model

from django.db.models import Sum
from django.db.models.functions import ExtractMonth, ExtractYear

from .forms import (
    ReadingForm,
    AddCounterForm,
    AddCounterPriceForm,
    AddCounterReadingForm,
    UpdateCounterForm,
)
from .models import Counter, Reading, Price, Payment

from django.db.models import OuterRef, Subquery, Max


def index_view(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse("counters:dashboard"))
    else:
        return render(request, "counters/index.html")


def login_view(request):
    if request.method == "POST":
        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("counters:dashboard"))
        else:
            return render(
                request,
                "counters/login.html",
                {"message": "Invalid username and/or password."},
            )
    else:
        return render(request, "counters/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("counters:login"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        if not username:
            return render(
                request, "counters/register.html", {"message": "Username is required"}
            )

        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if len(password) < 8:
            return render(
                request,
                "counters/register.html",
                {"message": "Passwords must contain at least 8 characters."},
            )

        if password != confirmation:
            return render(
                request, "counters/register.html", {"message": "Passwords must match."}
            )

        # Attempt to create new user
        try:
            user = get_user_model().objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(
                request,
                "counters/register.html",
                {"message": "Username already taken."},
            )
        login(request, user)
        return HttpResponseRedirect(reverse("counters:dashboard"))
    else:
        return render(request, "counters/register.html")


class CounterDetailView(DetailView):
    model = Counter

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(user=self.request.user)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        counter = context["object"]
        readings = (
            Reading.objects.filter(counter=counter, usage__gt=0)
            .annotate(month=ExtractMonth("date"))
            .values("month", "usage")
            .order_by("date")
        )
        readings_month = [
            calendar.month_name[reading.get("month")] for reading in readings
        ]
        readings_usage = [float(reading.get("usage")) for reading in readings]

        context["readings_month"] = readings_month
        context["readings_usage"] = readings_usage
        return context


class AddCounter(LoginRequiredMixin, CreateView):
    form_class = AddCounterForm
    template_name = "counters/generic_update.html"
    success_url = reverse_lazy("counters:dashboard")

    def form_valid(self, form):
        if form.is_valid():
            form.instance.user = self.request.user
            response = super().form_valid(form)

            # Get the counter by its name
            counter_name = form.cleaned_data["title"]
            try:
                counter = Counter.objects.get(
                    user=self.request.user, title=counter_name
                )
            except Counter.DoesNotExist:
                # Handle the case when the counter with the given name doesn't exist
                # (e.g., show an error message or redirect to an error page)
                raise ValueError("Counter with the given name does not exist.")

            # Validate the AddCounterPriceForm
            price_form = AddCounterPriceForm(self.request.POST)
            if price_form.is_valid():
                Price.objects.create(
                    counter=counter,
                    date=form.cleaned_data["initial_date"],
                    price_per_unit=price_form.cleaned_data["price_per_unit"],
                    price_per_month=price_form.cleaned_data["price_per_month"],
                )

            # Validate the AddCounterReadingForm
            reading_form = AddCounterReadingForm(self.request.POST)
            if reading_form.is_valid():
                Reading.objects.create(
                    counter=counter,
                    date=form.cleaned_data["initial_date"],
                    value=reading_form.cleaned_data["value"],
                )

            return response
        return self.form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context[
            "price_form"
        ] = AddCounterPriceForm()  # Include the CounterPriceForm in the context
        context["reading_form"] = AddCounterReadingForm()
        return context


class SummaryView(ListView):
    model = Counter
    template_name = "counters/summary.html"

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(user=self.request.user)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        latest_reading_date = latest_reading_date_for_user_counters(self.request.user)
        if latest_reading_date:
            context["latest_reading_date"] = latest_reading_date.strftime("%Y-%m-%d")
        context["counter_form"] = AddCounterForm()
        context["payments_per_month"] = (
            Reading.objects.filter(counter__user=self.request.user, usage__gt=0)
            .annotate(month=ExtractMonth("date"), year=ExtractYear("date"))
            .values("month", "year")
            .annotate(total_payment=Sum("payment__amount"))
            .order_by("month")
        )
        return context


def latest_reading_date_for_user_counters(user):
    return Reading.objects.filter(counter__user=user).aggregate(
        latest_date=Max("date")
    )["latest_date"]


def add_readings(request):
    if request.method == "POST":
        readings_date = datetime.strptime(request.POST.get("date"), "%Y-%m-%d")
        for counter in request.user.counters.all():
            # Only one reading per month if this not initial reading
            if counter.readings.exists() and counter.readings.count() > 1:
                latest_reading = counter.readings.latest("pk")

                # Return HttpResponseBadRequest if value of previous reading i greater then new value
                if float(latest_reading.value) > float(request.POST.get(counter.title)):
                    return HttpResponseBadRequest()

                # Delete the latest reading if reading in same month
                if latest_reading.date.month == readings_date.month:
                    latest_reading.delete()

            Reading.objects.create(
                counter=counter,
                date=readings_date,
                value=request.POST.get(counter.title),
            )

            latest_reading = counter.readings.latest("pk")

            # Adding Payment
            Payment.objects.create(
                counter=counter,
                reading=latest_reading,
                price=counter.prices.last(),
                amount=calculate_reading_payment(latest_reading),
            )

        return redirect(reverse_lazy("counters:dashboard"))


def calculate_reading_payment(reading):
    if reading.get_previous_reading():
        if reading.usage_in_units():
            total = reading.usage_in_units() * float(
                reading.counter.prices.last().price_per_unit
            )
            return (
                total + float(reading.counter.prices.last().price_per_month)
                if reading.counter.prices.last().price_per_month
                else total
            )
        return reading.counter.prices.last().price_per_month


class CounterUpdateView(UpdateView):
    form_class = UpdateCounterForm
    template_name = "counters/generic_update.html"

    def get_queryset(self):
        return Counter.objects.filter(user=self.request.user)

    def get_success_url(self):
        return reverse_lazy("counters:counter-detail", kwargs={"pk": self.object.pk})

capstone/counters/templates/counters/partials/counters_table.html
{% if counters %}
<h5 class="card-title">Counters</h5>
<table class='table table-hover'>
    <thead>
    <tr>
        <th>Title</th>
        <th>Price per unit</th>
        <th>Fixed price</th>
    </tr>
    </thead>
    <tbody>
    {% for counter in counters %}
    <tr>
        <td>
            <a href="{% url 'counters:counter-detail' counter.id %}">{{ counter.title }}</a>
        </td>
        <td>
            {% if counter.prices.last.price_per_unit %}
            {{ counter.prices.last.price_per_unit }} zł/{{ counter.unit }}{% endif %}
        </td>
        <td>
            {% if counter.prices.last.price_per_month %}{{ counter.prices.last.price_per_month }} zł{% endif %}
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
<h5 class="card-title">No counters for now...</h5>
{% endif %}

capstone/counters/templates/counters/partials/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

capstone/counters/templates/counters/partials/readings_add_modal.html
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#readingsModal">
    Calculate payments
</button>

<!-- Modal -->
<div class="modal fade " id="readingsModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="post" action="{% url 'counters:readings-add' %}">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Calculate payments</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <h5 class="card-title"></h5>
                    {% csrf_token %}
                    <div class="form-floating mb-3">
                        <input required type="date" class="form-control" id="date" name="date"
                               min="{{ latest_reading_date }}">
                    </div>
                    {% for object in object_list %}
                    {% with counter=object %}
                    <div class="form-floating mb-3">
                        <input required type="number" step="0.01" class="form-control" name="{{ counter.title }}"
                               id="{{ counter.title }}" min="{{ counter.readings.first.value }}">
                        <label for="{{ counter.title }}">{{ counter.title }}</label>
                    </div>
                    {% endwith %}
                    {% endfor %}

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>

capstone/counters/templates/counters/partials/readings_table.html
<div class="card border-0 shadow rounded">
    <div class="card-body">
        {% if readings %}
        <h5 class="card-title">Readings</h5>

        <table class="table table-hover">
            <thead>
            <tr>
                <th>Date</th>
                <th>Value</th>
                <th>Usage</th>
                <th>Payment</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for reading in readings %}
            <tr>
                <td>{{ reading.date }}</td>
                <td>{{ reading.value }} {{ reading.counter.unit }}</td>

                {% if reading %}
                <td>{{ reading.usage|floatformat:2 }} {{ counter.unit }}</td>
                {% else %}
                <td>-</td>
                {% endif %}

                {% if reading.payment %}
                <td>{{ reading.payment.amount|floatformat:2 }} zł</td>
                {% else %}
                <td>-</td>
                {% endif %}
                <td>
                    <a href="{% url 'counters:reading-delete' reading.id %}">delete</a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
        {% include 'counters/partials/pagination.html' %}
        {% else %}
        <h5 class="card-title">No readings for now...</h5>

        {% endif %}
    </div>
</div>